language: android
jdk: oraclejdk8
sudo: required

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager "platforms;android-27"

branches:
  only:
    - master

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

script:
  - cd Neato-SDK
  - ./gradlew :neato-sdk-android:clean :neato-sdk-android:assembleDebug :neato-sdk-android:testDebug
